version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQATESTAzStage2006Project
  gitServerName: KusiTestAzStageVC
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
