version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQATESTAzStage2006Project
  gitServerName: KusiTestAzStageVC
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
services:
- serviceName: project.siqatestazstage2006.integrations:AlertsCRTandERT
  packages:
  - name: SIQATESTAzStage2006Project
    version: "1.0"
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 11.1.0.0.2040
- serviceName: project.siqatestazstage2006.integrations:childFS
  packages:
  - name: SIQATESTAzStage2006Project
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2040
- serviceName: project.siqatestazstage2006.integrations:deepclonetest
  packages:
  - name: SIQATESTAzStage2006Project
    version: "1.0"
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 11.1.0.0.2040
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 11.1.0.0.2040
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2040
- serviceName: project.siqatestazstage2006.integrations:parentFS
  packages:
  - name: SIQATESTAzStage2006Project
    version: "1.0"
